In [17]:
import numpy as np
#Slicing Of An Arrray
arr=np.array([1,2,3,4,5,6,7,8,9])
slice1=arr[2:6]
print(slice1)
#Slice with step of 2 
slice2=arr[::2]
print(slice2)
reversed=arr[::-1]
#reverse
print(reversed)
#Slicing Multidiminesional array
arr=np.array([[1,2,3],[4,5,6],[7,8,9]])
subarray=arr[0:2,1:3]
print(subarray)

[3 4 5 6]
[1 3 5 7 9]
[9 8 7 6 5 4 3 2 1]
[[2 3]
 [5 6]]


In [17]:
import numpy as np
arr=np.array([[1,2,3],[4,5,6],[7,8,9]])
col=arr[:,0]
print(col)
print(arr[0,0])
print(arr[1,2])
#Indexing Techniques
#Very First One IS Basic Indexing

[1 4 7]
1
6


In [31]:
import numpy as np
arr=np.array([4,5,3,4,5,7,3,7,4,6])
print(arr[1])
#Negative Indexing
arr=np.array([4,5,3,4,5,7,3,7,4,6])
print(arr[-1])
#index element that needs a specific conditions
print(arr[arr>5])

5
6
[7 7 6]


In [41]:
import numpy as np
arr=np.array([10,20,0,40,50,60])
arr1=np.array([[1,2],[3,4]])
print(arr1)
arr2=np.array([[5,6],[7,8]])
result=np.hstack((arr1,arr2))
print(result)
#Vertical Join - adds elements at the top of each other
arr=np.array([10,20,0,40,50,60])
arr1=np.array([[1,2],[3,4]])
print(arr1)
arr2=np.array([[5,6],[7,8]])
result=np.vstack((arr1,arr2))
print(result)

[[1 2]
 [3 4]]
[[1 2 5 6]
 [3 4 7 8]]
[[1 2]
 [3 4]]
[[1 2]
 [3 4]
 [5 6]
 [7 8]]


In [47]:
import numpy as np
arr=np.array([10,20,0,40,50,60])
otpt=np.split(arr,3)
print(otpt)
#Splitting Unequal Parts
array_

[array([10, 20]), array([ 0, 40]), array([50, 60])]


In [49]:
import numpy as np
arr=np.array([10,20,0,40,50,60,70])
otpt=np.array_split(arr,3)
print(otpt)

[array([10, 20,  0]), array([40, 50]), array([60, 70])]
