In [3]:
import numpy as np
arr=np.array([1,6,2,7,6,4])
x=np.where(arr==6)
print(x)


(array([1, 4]),)


In [5]:
import numpy as np
arr=np.array([1,6,2,7,6,4])
x=np.where(arr==7)
print(x)

(array([3]),)


In [7]:
import numpy as np
arr=np.array([0,1,2,2,7,8,9])
x=np.searchsorted(arr,3,side='left')
print(x)

4


In [9]:
import numpy as np
arr=np.array([0,1,2,2,7,8,9])
x=np.searchsorted(arr,8,side='right')
print(x)

6


In [12]:
import numpy as np
arr=np.array([9,5,2,7,6,4])
print(np.sort(arr))

[2 4 5 6 7 9]


In [13]:
a=np.array([[7,4,9],[9,1,4]])
print(np.sort(a))

[[4 7 9]
 [1 4 9]]


In [30]:
import numpy as np
arr=np.array([32,78,69,88])
x[False,True,False,True]
 

array([], dtype=int32)

In [26]:
import numpy as np
arr=np.array([32,78,69,88])
filter_arr=arr<70
newarr=arr[filter_arr]
print(filter_arr)
print(newarr)

[ True False  True False]
[32 69]
