In [1]:
import numpy as np
a=np.array([10,20,30,40,50])
print("One dimensional array:",a)

One dimensional array: [10 20 30 40 50]


In [2]:
import numpy as np
a=np.array([[10,20,30,40,50],[60,70,80,90,100]])
print("Two dimensional array:",a)

Two dimensional array: [[ 10  20  30  40  50]
 [ 60  70  80  90 100]]


In [3]:
import numpy as np
a=np.zeros((3,5))
print("\n Array with all zeros:\n",a)


 Array with all zeros:
 [[0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]]


In [4]:
import numpy as np
d=np.random.random((3,3))
print("\n Random value:",d)


 [[0.17691653 0.3919634  0.06870325]
 [0.30401085 0.49154608 0.95058846]
 [0.60434898 0.30325038 0.76835335]]


In [5]:
import numpy as np
e=np.arange(0,10,1)
print("\n Range value :\n",e)


 Range value :
 [0 1 2 3 4 5 6 7 8 9]


In [6]:
import numpy as np
arr=np.array([[1,2,3,4],[5,2,4,2],[1,2,0,1]])
newarr=arr.reshape((4,3))
print("\n Original array:",arr)
print("\n Reshaped array:",newarr)
newtype=arr.astype('f')
print("converted array element:\n",newtype)
print("converted array:" ,newtype.dtype)
size=len(arr)
print("\n size of array:\n",size)


 [[1 2 3 4]rray:
 [5 2 4 2]
 [1 2 0 1]]

 [[1 2 3] array:
 [4 5 2]
 [4 2 1]
 [2 0 1]]
converted array element:
 [[1. 2. 3. 4.]
 [5. 2. 4. 2.]
 [1. 2. 0. 1.]]
converted array: float32

 size of array:
 3


In [7]:
import numpy as np
a=np.zeros((5,3))
print("\n Array with 5x3 with all zeros:\n",a)


 Array with 5x3 with all zeros:
 [[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]


In [8]:
import numpy as np
a=np.random.random((5,3))
print("\n Array with 5x3 with all Random Numbers:\n",a)


 Array with 5x3 with all Random Numbers:
 [[0.59431025 0.91479572 0.0786085 ]
 [0.31119936 0.85728049 0.64630979]
 [0.89653694 0.77858854 0.62851361]
 [0.80930244 0.04511761 0.28197896]
 [0.28639755 0.04254405 0.67254327]]


In [9]:
import numpy as np
arr=np.array([[0.56347699, 0.00142372, 0.34454864],
[0.45750291,0.77197486, 0.72972187],
[0.41213894, 0.61247472, 0.24462655],
[0.97781793, 0.35785797, 0.99369307],
[0.8228994,  0.77176082, 0.41449275]])
newarr=arr.reshape((3,5))
print("\n Original array:",arr)
print("\n Reshaped array:",newarr)


 [[0.56347699 0.00142372 0.34454864]
 [0.45750291 0.77197486 0.72972187]
 [0.41213894 0.61247472 0.24462655]
 [0.97781793 0.35785797 0.99369307]
 [0.8228994  0.77176082 0.41449275]]

 [[0.56347699 0.00142372 0.34454864 0.45750291 0.77197486]
 [0.72972187 0.41213894 0.61247472 0.24462655 0.97781793]
 [0.35785797 0.99369307 0.8228994  0.77176082 0.41449275]]


In [10]:
import numpy as np
arr=np.array([[1,2,3,4],[5,2,4,2],[1,2,0,1]])
newarr=arr.reshape((4,3))
print("\n Original array:",arr)
print("\n Reshaped array:",newarr)
print("\n No. of diminsions: ",arr.ndim)


 [[1 2 3 4]rray:
 [5 2 4 2]
 [1 2 0 1]]

 [[1 2 3] array:
 [4 5 2]
 [4 2 1]
 [2 0 1]]

 2o. of diminsions: 


In [11]:
flat=arr.flatten()
print("Flattened Array: \n",flat)

Flattened Array: 
 [1 2 3 4 5 2 4 2 1 2 0 1]


In [12]:
print("\n Shape of array :",arr.shape)


 (3, 4)of array :


In [13]:
print("\n array element type:",arr.dtype)


 int32 element type:


In [16]:
newtype=arr. astype('f')
print("\n count array element:\n",newtype)
print("converted array:",newtype.dtype)


 count array element:
 [[1. 2. 3. 4.]
 [5. 2. 4. 2.]
 [1. 2. 0. 1.]]
converted array: float32


In [17]:
size=len(arr)
print("\n size of array\n",size)


 size of array
 3
